ocs_expected_crds:
- backingstores.noobaa.io
- bucketclasses.noobaa.io
- noobaas.noobaa.io
- objectbucketclaims.objectbucket.io
ocs_channel: stable-4.2
ocs_install_mcg: true
ocs_mcg_core_cpu: 0.5
ocs_mcg_core_mem: 500Mi
ocs_mcg_db_cpu: 0.5
ocs_mcg_db_mem: 1Gi
ocs_ceph_mds_cpu: 0.5
ocs_ceph_mds_mem: 1Gi
ocs_ceph_mon_cpu: 0.5
ocs_ceph_mon_mem: 1Gi
ocs_ceph_mgr_cpu: 0.5
ocs_ceph_mgr_mem: 1Gi
ocs_ceph_osd_cpu: 0.5
ocs_ceph_osd_mem: 1Gi
ocs_mcg_pv_pool: true
ocs_mcg_pv_pool_bucket_name: mcg
ocs_mcg_pv_pool_pv_size: 50Gi
ocs_mcg_pv_pool_pv_quantity: 3
ocs_mcg_pv_pool_pv_storageclass: gp2
ocs_namespace: openshift-storage
ocs_release: v4.2.2
ocs_operator_workload_destroy: "{{ False if (ACTION=='create' or ACTION=='provision') else True }}"
silent: false

# Custom notebook image source that will be used for the workshop
workshop_jupyter_notebook_imagestream_image: "quay.io/llasmith/spark-notebook:spark-2.3.2_hadoop-2.8.5"
# Imagestream name for the custom workshop image
workshop_jupyter_notebook_imagestream_name: "ml-workflows-notebook"
# Imagestream tag for the custom workshop image
workshop_jupyter_notebook_imagestream_tag: "latest"

# Command separated string list each git repo url to preload on the notebook pod when it spawns
workshop_preload_repos: "https://github.com/willb/ml-workflows-notebook"

och_project: open-data-hub
user_project: user
workload_destroy: false

och_expected_crds:
- opendatahubs.opendatahub.io

knative_expected_crds:
- knativeservings.operator.knative.dev

install_storage: false
install_open_data_hub: true
install_postgres: false
install_codeready: false
install_knative: true
install_pipelines: true

# The first user number to start with when creating projects
user_count_start: 1
# The last user number to start with when creating projects
user_count_end: "{{user_count_start|int + num_users|int}}"
