---
- name: "Create Subscription"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'serverless/subscription.yml.j2') }}"
  vars:
    namespace: "{{ user_project }}"

- name: "Create Namespace"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'general/namespace.yml.j2') }}"
  vars:
    namespace: knative-serving

- name: "Create Knative"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'serverless/knative.yml.j2') }}"
  vars:
    namespace: knative-serving 